server:
  port: 8189

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/appointments_db
    username: postgres
    password: 123456

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
